# Generated by Django 5.1.6 on 2025-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='descriptionn',
            field=models.CharField(blank=True, default='Описание задачи', max_length=255),
        ),
    ]
