# Generated by Django 5.1.6 on 2025-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0002_alter_tasks_descriptionn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='time_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
