# Generated by Django 5.1.6 on 2025-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0003_alter_tasks_time_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='descriptionn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
