# Generated by Django 5.1.6 on 2025-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('title', models.CharField(default='Название задачи', max_length=25)),
                ('descriptionn', models.CharField(default='Описание задачи', max_length=255)),
                ('statuss', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_finish', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
